name: infra
on:
  pull_request: { paths: [ 'infra/**' ] }
  push: { branches: [ main ], paths: [ 'infra/**' ] }
permissions: { id-token: write, contents: read }
jobs:
  tf:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: infra } }
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          {% raw -%}
          role-to-assume: ${{ secrets.AWS_GHA_ROLE_ARN }}
          {% endraw -%}
          aws-region: {{ cookiecutter.aws_region }}
      - run: terraform init -input=false
      - run: terraform fmt -check
      - run: terraform validate
      - if: github.event_name == 'pull_request'
        run: terraform plan -input=false
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
